# additional cluster roles for kyverno
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno-kyverno
    app.kubernetes.io/part-of: kyverno-kyverno
  name: kyverno:create-deployments
rules:
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - create
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/component: background-controller
    app.kubernetes.io/instance: kyverno-kyverno
    app.kubernetes.io/part-of: kyverno-kyverno
  name: kyverno:write-deployments
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - update
