apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-apps-user-nodepools-existing
spec:
  mutateExistingOnPolicyUpdate: true
  rules:
  - name: find-pods-no-node-spec-existing
    match:
      any:
      - resources:
          kinds:
          - Deployment
          namespaces:
          - "ns-*"
          - "default"
    mutate:
      targets:
      - apiVersion: apps/v1
        kind: Deployment
        name: "{{ request.object.metadata.name }}"
        namespace: "{{ request.object.metadata.namespace }}"
      patchStrategicMerge:
        spec:
          template: 
            spec:
              nodeSelector:
                +(kubernetes.azure.com/mode): user
