apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: mutate-apps-user-nodepools
spec:
  rules:
  - name: find-pods-no-node-spec
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          #- "ns-*"
          - "default"
    mutate:
      patchStrategicMerge:
        spec:
          nodeSelector:
            +(kubernetes.azure.com/mode): user
